-- Edition-specific encounter shares; each regular area totals 100 percent.
return {
  red = {
    ['HIDDEN_GROVE_01'] = {
      {['excludeIfStarter']=true,['species']='BULBASAUR',['fallbackSpecies']='CATERPIE',['weight']=5},
      {['weight']=13,['species']='CATERPIE'},
      {['weight']=15,['species']='WEEDLE'},
      {['weight']=14,['species']='PARAS'},
      {['weight']=12,['species']='EXEGGCUTE'},
      {['weight']=14,['species']='BELLSPROUT'},
      {['weight']=7,['species']='WEEPINBELL'},
      {['weight']=2,['species']='VICTREEBEL'},
      {['weight']=8,['species']='PIKACHU'},
      {['weight']=8,['species']='PINSIR'},
      {['weight']=2,['species']='SCYTHER'},
    },
    ['ROCKY_SUMMIT_01'] = {
      {['excludeIfStarter']=true,['species']='CHARMANDER',['fallbackSpecies']='GEODUDE',['weight']=5},
      {['weight']=19,['species']='GEODUDE'},
      {['weight']=18,['species']='ZUBAT'},
      {['weight']=16,['species']='MACHOP'},
      {['weight']=10,['species']='ONIX'},
      {['weight']=12,['species']='SANDSHREW'},
      {['weight']=5,['species']='SANDSLASH'},
      {['weight']=7,['species']='MAGMAR'},
      {['weight']=3,['species']='MACHAMP'},
      {['weight']=3,['species']='GOLEM'},
      {['weight']=2,['species']='RHYHORN'},
    },
    ['SECRET_SHORE_01'] = {
      {['excludeIfStarter']=true,['species']='SQUIRTLE',['fallbackSpecies']='TENTACOOL',['weight']=5},
      {['weight']=19,['species']='TENTACOOL'},
      {['weight']=18,['species']='KRABBY'},
      {['weight']=16,['species']='SHELLDER'},
      {['weight']=14,['species']='HORSEA'},
      {['weight']=10,['species']='STARYU'},
      {['weight']=7,['species']='SLOWPOKE'},
      {['weight']=7,['species']='MEOWTH'},
      {['weight']=2,['species']='PERSIAN'},
      {['weight']=2,['species']='SEEL'},
    },
    ['QUIET_POND_01'] = {
      {['weight']=22,['species']='POLIWAG'},
      {['weight']=18,['species']='PSYDUCK'},
      {['weight']=15,['species']='GOLDEEN'},
      {['weight']=12,['species']='SLOWPOKE'},
      {['weight']=9,['species']='VENONAT'},
      {['weight']=7,['species']='DRATINI'},
      {['weight']=6,['species']='GASTLY'},
      {['weight']=5,['species']='HAUNTER'},
      {['weight']=3,['species']='GENGAR'},
      {['weight']=3,['species']='EXEGGCUTE'},
    },
    ['OLD_CLEARING_01'] = {
      {['weight']=18,['species']='ABRA'},
      {['weight']=8,['species']='KADABRA'},
      {['weight']=3,['species']='ALAKAZAM'},
      {['weight']=13,['species']='CLEFAIRY'},
      {['weight']=14,['species']='VULPIX'},
      {['weight']=4,['species']='NINETALES'},
      {['weight']=8,['species']='CHANSEY'},
      {['weight']=6,['species']='EEVEE'},
      {['weight']=13,['species']='NIDORAN_F'},
      {['weight']=13,['species']='NIDORAN_M'},
    },
  },
  blue = {
    ['HIDDEN_GROVE_01'] = {
      {['excludeIfStarter']=true,['species']='BULBASAUR',['fallbackSpecies']='CATERPIE',['weight']=5},
      {['weight']=13,['species']='CATERPIE'},
      {['weight']=15,['species']='WEEDLE'},
      {['weight']=14,['species']='PARAS'},
      {['weight']=12,['species']='EXEGGCUTE'},
      {['weight']=14,['species']='ODDISH'},
      {['weight']=7,['species']='GLOOM'},
      {['weight']=2,['species']='VILEPLUME'},
      {['weight']=8,['species']='PIKACHU'},
      {['weight']=8,['species']='SCYTHER'},
      {['weight']=2,['species']='PINSIR'},
    },
    ['ROCKY_SUMMIT_01'] = {
      {['excludeIfStarter']=true,['species']='CHARMANDER',['fallbackSpecies']='GEODUDE',['weight']=5},
      {['weight']=19,['species']='GEODUDE'},
      {['weight']=18,['species']='ZUBAT'},
      {['weight']=16,['species']='MACHOP'},
      {['weight']=10,['species']='ONIX'},
      {['weight']=12,['species']='EKANS'},
      {['weight']=5,['species']='ARBOK'},
      {['weight']=7,['species']='ELECTABUZZ'},
      {['weight']=3,['species']='MACHAMP'},
      {['weight']=3,['species']='GOLEM'},
      {['weight']=2,['species']='RHYHORN'},
    },
    ['SECRET_SHORE_01'] = {
      {['excludeIfStarter']=true,['species']='SQUIRTLE',['fallbackSpecies']='TENTACOOL',['weight']=5},
      {['weight']=19,['species']='TENTACOOL'},
      {['weight']=18,['species']='KRABBY'},
      {['weight']=16,['species']='SHELLDER'},
      {['weight']=14,['species']='HORSEA'},
      {['weight']=10,['species']='STARYU'},
      {['weight']=7,['species']='SLOWPOKE'},
      {['weight']=7,['species']='MANKEY'},
      {['weight']=2,['species']='PRIMEAPE'},
      {['weight']=2,['species']='SEEL'},
    },
    ['QUIET_POND_01'] = {
      {['weight']=22,['species']='POLIWAG'},
      {['weight']=18,['species']='PSYDUCK'},
      {['weight']=15,['species']='GOLDEEN'},
      {['weight']=12,['species']='SLOWPOKE'},
      {['weight']=9,['species']='VENONAT'},
      {['weight']=7,['species']='DRATINI'},
      {['weight']=6,['species']='GASTLY'},
      {['weight']=5,['species']='HAUNTER'},
      {['weight']=3,['species']='GENGAR'},
      {['weight']=3,['species']='EXEGGCUTE'},
    },
    ['OLD_CLEARING_01'] = {
      {['weight']=18,['species']='ABRA'},
      {['weight']=8,['species']='KADABRA'},
      {['weight']=3,['species']='ALAKAZAM'},
      {['weight']=13,['species']='CLEFAIRY'},
      {['weight']=14,['species']='GROWLITHE'},
      {['weight']=4,['species']='ARCANINE'},
      {['weight']=8,['species']='CHANSEY'},
      {['weight']=6,['species']='EEVEE'},
      {['weight']=13,['species']='NIDORAN_F'},
      {['weight']=13,['species']='NIDORAN_M'},
    },
  },
  yellow = {
    ['HIDDEN_GROVE_01'] = {
      {['species']='BULBASAUR',['weight']=5},
      {['species']='CATERPIE',['weight']=13},
      {['species']='WEEDLE',['weight']=10},
      {['species']='KAKUNA',['weight']=3},
      {['species']='BEEDRILL',['weight']=2},
      {['species']='PARAS',['weight']=14},
      {['species']='EXEGGCUTE',['weight']=12},
      {['species']='BELLSPROUT',['weight']=14},
      {['species']='WEEPINBELL',['weight']=7},
      {['species']='VICTREEBEL',['weight']=2},
      {['species']='TANGELA',['weight']=8},
      {['species']='PINSIR',['weight']=8},
      {['species']='SCYTHER',['weight']=2},
    },
    ['ROCKY_SUMMIT_01'] = {
      {['species']='CHARMANDER',['weight']=5},
      {['species']='GEODUDE',['weight']=15},
      {['species']='ZUBAT',['weight']=15},
      {['species']='MACHOP',['weight']=16},
      {['species']='ONIX',['weight']=10},
      {['species']='EKANS',['weight']=12},
      {['species']='ARBOK',['weight']=5},
      {['species']='MAGMAR',['weight']=7},
      {['species']='ELECTABUZZ',['weight']=7},
      {['species']='MACHAMP',['weight']=3},
      {['species']='GOLEM',['weight']=3},
      {['species']='RHYHORN',['weight']=2},
    },
    ['SECRET_SHORE_01'] = {
      {['species']='SQUIRTLE',['weight']=5},
      {['species']='TENTACOOL',['weight']=18},
      {['species']='KRABBY',['weight']=18},
      {['species']='SHELLDER',['weight']=16},
      {['species']='HORSEA',['weight']=14},
      {['species']='STARYU',['weight']=10},
      {['species']='SLOWPOKE',['weight']=7},
      {['species']='MEOWTH',['weight']=7},
      {['species']='PERSIAN',['weight']=2},
      {['species']='JYNX',['weight']=3},
    },
    ['QUIET_POND_01'] = {
      {['species']='POLIWAG',['weight']=19},
      {['species']='PSYDUCK',['weight']=15},
      {['species']='GOLDEEN',['weight']=15},
      {['species']='SLOWPOKE',['weight']=9},
      {['species']='VENONAT',['weight']=9},
      {['species']='DRATINI',['weight']=7},
      {['species']='GASTLY',['weight']=6},
      {['species']='HAUNTER',['weight']=5},
      {['species']='GENGAR',['weight']=3},
      {['species']='EXEGGCUTE',['weight']=3},
      {['species']='KOFFING',['weight']=6},
      {['species']='WEEZING',['weight']=3},
    },
    ['OLD_CLEARING_01'] = {
      {['species']='ABRA',['weight']=18},
      {['species']='KADABRA',['weight']=8},
      {['species']='ALAKAZAM',['weight']=3},
      {['species']='CLEFAIRY',['weight']=10},
      {['species']='VULPIX',['weight']=14},
      {['species']='NINETALES',['weight']=4},
      {['species']='CHANSEY',['weight']=8},
      {['species']='EEVEE',['weight']=6},
      {['species']='NIDORAN_F',['weight']=13},
      {['species']='NIDORAN_M',['weight']=13},
      {['species']='RAICHU',['weight']=3},
    },
  },
}
