-- Authored Red stock-map content; positions are anchors, rewards remain instance-scoped.
return {areas={
    {
      id='HIDDEN_GROVE_01',name='HIDDEN GROVE',saveKey='hidden_grove_01',kind='regular',
      music='Music_Routes1',mapId='SWR_HIDDEN_GROVE_01',mapIndex=1000,template='grove',marker='grove',
      tags={'forest','plains'},weight=3,repeatable=true,
      visibleWhen='active',landableWhen='active',completeWhen='exit',
      approachRadius=78,landingRadius=38,landingPoint={x=9,y=12},
      reward={item='GREAT_BALL',index=1,x=12,y=8},
      rewardProfiles={
        common={weight=70,items={'GREAT_BALL','SUPER_POTION','FULL_HEAL','SUPER_REPEL','ESCAPE_ROPE'}},
        rare={weight=25,items={'MAX_REVIVE','MAX_REVIVE','ULTRA_BALL','HYPER_POTION','MAX_REPEL','MAX_ETHER','ELIXER','LEAF_STONE'}},
        special={weight=5,items={'MAX_REVIVE','MAX_REVIVE','FULL_RESTORE','RARE_CANDY','PP_UP','LEAF_STONE'}},
      },
      encounterPool={{species='BULBASAUR',weight=5,excludeIfStarter=true,fallbackSpecies='CATERPIE'},{species='CATERPIE',weight=13},{species='WEEDLE',weight=15},{species='PARAS',weight=14},{species='EXEGGCUTE',weight=12},{species='BELLSPROUT',weight=14},{species='WEEPINBELL',weight=7},{species='VICTREEBEL',weight=2},{species='PIKACHU',weight=8},{species='PINSIR',weight=8},{species='SCYTHER',weight=2}},
      encounterProfiles={{id='common',rate=18,level=22,maxLevel=30,species={'BULBASAUR','CATERPIE','WEEDLE','PARAS','EXEGGCUTE','BELLSPROUT','WEEPINBELL','VICTREEBEL','PIKACHU','PINSIR','SCYTHER'}},{id='rare',rate=18,level=31,maxLevel=39,species={'BULBASAUR','CATERPIE','WEEDLE','PARAS','EXEGGCUTE','BELLSPROUT','WEEPINBELL','VICTREEBEL','PIKACHU','PINSIR','SCYTHER'}},{id='special',rate=18,level=40,maxLevel=45,species={'BULBASAUR','CATERPIE','WEEDLE','PARAS','EXEGGCUTE','BELLSPROUT','WEEPINBELL','VICTREEBEL','PIKACHU','PINSIR','SCYTHER'}}},
    },
    {
      id='ROCKY_SUMMIT_01',name='ROCKY SUMMIT',saveKey='rocky_summit_01',kind='regular',
      music='Music_Dungeon3',mapId='SWR_ROCKY_SUMMIT_01',mapIndex=1001,template='summit',marker='summit',
      tags={'mountain'},weight=2,repeatable=false,
      visibleWhen='active',landableWhen='active',completeWhen='exit',
      approachRadius=78,landingRadius=38,landingPoint={x=9,y=12},
      reward={item='MAX_REVIVE',index=1,x=12,y=8},
      
      encounterPool={{species='CHARMANDER',weight=5,excludeIfStarter=true,fallbackSpecies='GEODUDE'},{species='GEODUDE',weight=19},{species='ZUBAT',weight=18},{species='MACHOP',weight=16},{species='ONIX',weight=10},{species='SANDSHREW',weight=12},{species='SANDSLASH',weight=5},{species='MAGMAR',weight=7},{species='MACHAMP',weight=3},{species='GOLEM',weight=3},{species='RHYHORN',weight=2}},
      encounterProfiles={{id='common',rate=18,level=22,maxLevel=30,species={'CHARMANDER','GEODUDE','ZUBAT','MACHOP','ONIX','SANDSHREW','SANDSLASH','MAGMAR','MACHAMP','GOLEM','RHYHORN'}},{id='rare',rate=18,level=31,maxLevel=39,species={'CHARMANDER','GEODUDE','ZUBAT','MACHOP','ONIX','SANDSHREW','SANDSLASH','MAGMAR','MACHAMP','GOLEM','RHYHORN'}},{id='special',rate=18,level=40,maxLevel=45,species={'CHARMANDER','GEODUDE','ZUBAT','MACHOP','ONIX','SANDSHREW','SANDSLASH','MAGMAR','MACHAMP','GOLEM','RHYHORN'}}},
    },
    {
      id='SECRET_SHORE_01',name='SECRET SHORE',saveKey='secret_shore_01',kind='regular',
      music='Music_Routes3',mapId='SWR_SECRET_SHORE_01',mapIndex=1002,template='shore',marker='shore',
      tags={'coast','island'},weight=2,repeatable=true,
      visibleWhen='active',landableWhen='active',completeWhen='exit',
      approachRadius=78,landingRadius=38,landingPoint={x=9,y=12},
      reward={item='GREAT_BALL',index=1,x=12,y=8},
      rewardProfiles={
        common={weight=70,items={'GREAT_BALL','SUPER_POTION','FULL_HEAL','SUPER_REPEL','ESCAPE_ROPE'}},
        rare={weight=25,items={'MAX_REVIVE','MAX_REVIVE','ULTRA_BALL','HYPER_POTION','MAX_REPEL','MAX_ETHER','ELIXER','WATER_STONE'}},
        special={weight=5,items={'MAX_REVIVE','MAX_REVIVE','FULL_RESTORE','RARE_CANDY','PP_UP','NUGGET'}},
      },
      encounterPool={{species='SQUIRTLE',weight=5,excludeIfStarter=true,fallbackSpecies='TENTACOOL'},{species='TENTACOOL',weight=19},{species='KRABBY',weight=18},{species='SHELLDER',weight=16},{species='HORSEA',weight=14},{species='STARYU',weight=10},{species='SLOWPOKE',weight=7},{species='MEOWTH',weight=7},{species='PERSIAN',weight=2},{species='SEEL',weight=2}},
      encounterProfiles={{id='common',rate=18,level=22,maxLevel=30,species={'SQUIRTLE','TENTACOOL','KRABBY','SHELLDER','HORSEA','STARYU','SLOWPOKE','MEOWTH','PERSIAN','SEEL'}},{id='rare',rate=18,level=31,maxLevel=39,species={'SQUIRTLE','TENTACOOL','KRABBY','SHELLDER','HORSEA','STARYU','SLOWPOKE','MEOWTH','PERSIAN','SEEL'}},{id='special',rate=18,level=40,maxLevel=45,species={'SQUIRTLE','TENTACOOL','KRABBY','SHELLDER','HORSEA','STARYU','SLOWPOKE','MEOWTH','PERSIAN','SEEL'}}},
    },
    {
      id='QUIET_POND_01',name='QUIET POND',saveKey='quiet_pond_01',kind='regular',
      music='Music_Dungeon2',mapId='SWR_QUIET_POND_01',mapIndex=1003,template='pond',marker='pond',
      tags={'forest','plains'},weight=2,repeatable=true,
      visibleWhen='active',landableWhen='active',completeWhen='exit',
      approachRadius=78,landingRadius=38,landingPoint={x=9,y=12},
      reward={item='GREAT_BALL',index=1,x=12,y=8},
      rewardProfiles={
        common={weight=70,items={'GREAT_BALL','SUPER_POTION','FULL_HEAL','SUPER_REPEL','ESCAPE_ROPE'}},
        rare={weight=25,items={'MAX_REVIVE','MAX_REVIVE','ULTRA_BALL','HYPER_POTION','MAX_REPEL','MAX_ETHER','ELIXER','THUNDER_STONE'}},
        special={weight=5,items={'MAX_REVIVE','MAX_REVIVE','FULL_RESTORE','RARE_CANDY','PP_UP','THUNDER_STONE'}},
      },
      encounterPool={{species='POLIWAG',weight=22},{species='PSYDUCK',weight=18},{species='GOLDEEN',weight=15},{species='SLOWPOKE',weight=12},{species='VENONAT',weight=9},{species='DRATINI',weight=7},{species='GASTLY',weight=6},{species='HAUNTER',weight=5},{species='GENGAR',weight=3},{species='EXEGGCUTE',weight=3}},
      encounterProfiles={{id='common',rate=18,level=22,maxLevel=30,species={'POLIWAG','PSYDUCK','GOLDEEN','SLOWPOKE','VENONAT','DRATINI','GASTLY','HAUNTER','GENGAR','EXEGGCUTE'}},{id='rare',rate=18,level=31,maxLevel=39,species={'POLIWAG','PSYDUCK','GOLDEEN','SLOWPOKE','VENONAT','DRATINI','GASTLY','HAUNTER','GENGAR','EXEGGCUTE'}},{id='special',rate=18,level=40,maxLevel=45,species={'POLIWAG','PSYDUCK','GOLDEEN','SLOWPOKE','VENONAT','DRATINI','GASTLY','HAUNTER','GENGAR','EXEGGCUTE'}}},
    },
    {
      id='OLD_CLEARING_01',name='OLD CLEARING',saveKey='old_clearing_01',kind='regular',
      music='Music_Routes2',mapId='SWR_OLD_CLEARING_01',mapIndex=1004,template='clearing',marker='clearing',
      tags={'forest','plains'},weight=2,repeatable=true,
      visibleWhen='active',landableWhen='active',completeWhen='exit',
      approachRadius=78,landingRadius=38,landingPoint={x=9,y=12},
      reward={item='GREAT_BALL',index=1,x=12,y=8},
      rewardProfiles={
        common={weight=70,items={'GREAT_BALL','SUPER_POTION','FULL_HEAL','SUPER_REPEL','ESCAPE_ROPE'}},
        rare={weight=25,items={'MAX_REVIVE','MAX_REVIVE','ULTRA_BALL','HYPER_POTION','MAX_REPEL','MAX_ETHER','ELIXER','MOON_STONE'}},
        special={weight=5,items={'MAX_REVIVE','MAX_REVIVE','FULL_RESTORE','RARE_CANDY','PP_UP','NUGGET'}},
      },
      encounterPool={{species='ABRA',weight=18},{species='KADABRA',weight=8},{species='ALAKAZAM',weight=3},{species='CLEFAIRY',weight=13},{species='VULPIX',weight=14},{species='NINETALES',weight=4},{species='CHANSEY',weight=8},{species='EEVEE',weight=6},{species='NIDORAN_F',weight=13},{species='NIDORAN_M',weight=13}},
      encounterProfiles={{id='common',rate=18,level=22,maxLevel=30,species={'ABRA','KADABRA','ALAKAZAM','CLEFAIRY','VULPIX','NINETALES','CHANSEY','EEVEE','NIDORAN_F','NIDORAN_M'}},{id='rare',rate=18,level=31,maxLevel=39,species={'ABRA','KADABRA','ALAKAZAM','CLEFAIRY','VULPIX','NINETALES','CHANSEY','EEVEE','NIDORAN_F','NIDORAN_M'}},{id='special',rate=18,level=40,maxLevel=45,species={'ABRA','KADABRA','ALAKAZAM','CLEFAIRY','VULPIX','NINETALES','CHANSEY','EEVEE','NIDORAN_F','NIDORAN_M'}}},
    },
    {
      id='FORGOTTEN_PIER_01',name='FORGOTTEN PIER',saveKey='forgotten_pier_01',kind='special',
      music='Music_Vermilion',mapId='SWR_FORGOTTEN_PIER_01',mapIndex=1005,
      template='pier',marker='pier',tags={'coast'},weight=1,repeatable=false,
      fixedAnchor={id='forgotten_vermilion_pier',x=1470,y=1323,tags={'coast'}},
      visibleWhen='active',landableWhen='active',completeWhen='exit',
      approachRadius=65,landingRadius=30,landingPoint={x=9,y=12},
      staticEncounter={species='MEW',level=70,index=2,x=10,y=8,sprite='SPRITE_MONSTER'},
      encounterProfiles={{id='static',rate=0,level=70,species={'MEW'}}},
    },
}}

